version: '3.8'

services:
  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/poll-app
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5000

volumes:
  mongo_data:
